enums.CreateShifted("INTENTS", {
	"GUILDS",
	"GUILD_MEMBERS",
	"GUILD_BANS",
	"GUILD_EMOJIS_AND_STICKERS",
	"GUILD_INTEGRATIONS",
	"GUILD_WEBHOOKS",
	"GUILD_INVITES",
	"GUILD_VOICE_STATES",
	"GUILD_PRESENCES",
	"GUILD_MESSAGES",
	"GUILD_MESSAGE_REACTIONS",
	"GUILD_MESSAGE_TYPING",
	"DIRECT_MESSAGES",
	"DIRECT_MESSAGE_REACTIONS",
	"DIRECT_MESSAGE_TYPING",
	"MESSAGE_CONTENT",
	"GUILD_SCHEDULED_EVENTS"
})

_G.INTENTS_DEFAULT = bit.bor(INTENTS_GUILDS, INTENTS_GUILD_MEMBERS, INTENTS_GUILD_WEBHOOKS, INTENTS_GUILD_MESSAGES, INTENTS_MESSAGE_CONTENT)
